flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


# the FlaskForm for creating a post. this will be passed in the return render_template as form=form
# from there, the html page will read and we can use {{}} to return any information passed into these forms
class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
'''
only the routes that are specific to homepage functionality will be included in this blueprint
'''
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)


# the @app decorator is the url link to each function
# in the bottom example, two decorators are declared "/" and "/home"
# the user can use either option to navigate back to the home page
@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)  # if users enter anything other than an int for a page, an error appears
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)  # this pagination will result in having only 5 post per page
    return render_template('home.html', posts=posts)  # the posts parameter can be used to loop through data. the for-loop is in the home.html file


# using "/about" will allow the user to navigate to the about page
@main.route("/about")
def about():
    return render_template('about.html', title='About')

flaskblog/posts/__init__.py
'''
creating an empty __init__ file so python knows this is a package
'''

flaskblog/posts/routes.py
'''
only the routes that are specific to posts functionality will be included in this blueprint
'''
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


# note, just like the users/routes.py blueprint, we are not using app.route. we are using posts.route and this will be registered to the application
# route to add new posts
@posts.route("/post/new", methods=['GET', 'POST'])
@login_required  # this is the decorator to require users to be logged in to route to this route
def new_post():
    form = PostForm()  # this creates the instants of the PostForm() class. you then pass this in the render_template
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created.', 'success')  # 'success' is the category
        return redirect(url_for('main.home'))  # redirect them the home page
    return render_template('new_post.html', title='Create a post', form=form, legend='Create post')


# routes the the post webpage. this is dynamic in that with each new post posted, a new /post/<int:post_id> is created
@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated.', 'success')  # a flash message
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('new_post.html', title='Update a post', form=form, legend='Update post')


# this deletes a post. however the post.html file with the bootstrap modal example is not working. not sure why
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)  # this is how to delete from the database which in turn deletes the post
    db.session.commit()
    flash('Your post has been deleted.', 'success')  # a flash message
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email
'''
only the routes that are specific to user functionality will be included in this blueprint
example: register, login, password reset, etc
'''

users = Blueprint('users', __name__)  #


# not using global 'app' variable to create the routes. creating routes specific to this 'users' blueprint, then register them to the application
@users.route("/register", methods=['GET', 'POST'])  # the methods list allows which type of html request to allow
def register():
    if current_user.is_authenticated:  # this will reroute users to the home page if they are already logged in
        return redirect(url_for('main.home'))
    form = RegistrationForm()

    # the validate_on_submit() method. this creates a user
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')  # form.password.data is the user input; this is hashed; it is also outputted as a string with passing of utf-8
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)  # this creates and stores a new user. NOTE, ONLY pass the hashed_pw NOT the form.password.data as that will capture the plain text entered password
        db.session.add(user)  # adding the newly created user to our database
        db.session.commit()  # committing the newly created user
        flash('Your account has been created.', 'success')  # the 'success' is a bootstrap Class
        return redirect(url_for('users.login'))  # this redirects the user to the login page

    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):  # check if the user exits and if the entered password matches the hash password in the database
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')  # this is only relevant if they navigate directly to the account page without being logged in. this will keep them on the account page instead of navigating them to the home page
            return redirect(next_page) if next_page else redirect(url_for('main.home')) # return the next_page if it exits, else return the homepage
        else:
            flash('Login Unsuccessful. Please check credentials and try again.', 'danger')  # 'danger' is a category for bootstrap as to how the flash() is the be displayed
    return render_template('login.html', title='Login', form=form)


# this will logout the current user
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


# this will allow users to only be able to see content if they are logged
@users.route("/account", methods=['GET', 'POST'])
@login_required  # this decorate tells flask that to navigate to account.html, the user needs to be logged in
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        db.session.commit()
        flash('Account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':  # this will populate both forms with the current user's data
        form.username.data = current_user.username
        form.email.data = current_user.email
    # current_user is a flask package; image_file is the variable located in the models.py file
    image_file = url_for('static', filename=f'profile_pic/{current_user.image_file}')  # 'static' is the directory; filename is the actual file name
    return render_template('account.html', title='Account', image_file=image_file, form=form)  # note, you can pass anything in render_template and have that variable be used in the html files


# this will show all and only the post from a specific author; the only clicked on
@users.route("/user/<string:username>")  # the <> makes this dynamic
def user_posts(username):
    page = request.args.get('page', 1, type=int)  # if users enter anything other than an int for a page, an error appears
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)  # this pagination will result in having only 5 post per page
    return render_template('user_posts.html', posts=posts, user=user)  # the posts parameter can be used to loop through data. the for-loop is in the home.html file


# route to request a reset of the password
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:  # the user must be logged out before resetting their password
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset your password.' 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


# this will reset their password with the token
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:  # the user must be logged out before resetting their password
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:  # this will check if the token a user uses has not expired yet
        flash('That token has expired.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')  # form.password.data is the user input; this is hashed; it is also outputted as a string with passing of utf-8
        user.password = hashed_pw
        db.session.commit()  # committing the changes
        flash('Your password has been updated.', 'success')  # the 'success' is a bootstrap Class
        return redirect(url_for('users.login'))  # this redirects the user to the login page

    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{  image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Information</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.email.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/home.html
<!-- this is called a template inheritance. creating a 'block' can be used to create for loops in html -->
<!-- 'block' works by overriding the child component with whatever is listed in the 'block' code -->
{% extends "layout.html" %}
{% block content %}  <!-- this 'block' is what will replace the 'block content' in the layout.html page -->
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages() %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!-- this is the parent template the other html pages will inherent from. this includes the main structure the other html pages will contain -->
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- this is the bootstrap starter tags -->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <meta charset="UTF-8">
    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
    <title>Title</title>
</head>
<body>
    <!-- this snippet is from Corey Schafer and adds navigation bars-->
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message}}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Please login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml -2">
                <a href="{{ url_for('users.reset_request') }}">Forgot password? Click here</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Do not have an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/new_post.html
{% extends "layout.html" %}
{% block content %}
 <div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flaskblog/templates/post.html
<!-- this is called a template inheritance. creating a 'block' can be used to create for loops in html -->
<!-- 'block' works by overriding the child component with whatever is listed in the 'block' code -->
{% extends "layout.html" %}
{% block content %}  <!-- this 'block' is what will replace the 'block content' in the layout.html page -->
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
           {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id)}}">Update</a>
                <button type="button" class="btn btn-primary btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
           {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/user_posts.html
<!-- this is called a template inheritance. creating a 'block' can be used to create for loops in html -->
<!-- 'block' works by overriding the child component with whatever is listed in the 'block' code -->
{% extends "layout.html" %}
{% block content %}  <!-- this 'block' is what will replace the 'block content' in the layout.html page -->
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages() %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}